### PR TITLE
DHT to akka

### PR DESCRIPTION
**Pull request by qurben**
Refactor the DHT to use akka, makes it a bit more flexible

### CODE REVIEW

**Comment by qurben** [comment]
The ring is now a `LazyList[RingNode]` which keeps looping around itself, this way the top-n method is trivial.

**Comment by Jimver** [comment]
Yes looks way better than my hacky implementation!

**Comment by TheBonheurs** [comment]
I agree! Should we merge?

**Comment by qurben** [comment]
Go ahead

**Pull request merged**
